### ISSUE TITLE
Setup Continuous Integration (CI) for Automatic Builds

### ISSUE THREAD

**Issue by AnthonyByansi** [Masembe0757/Capstone-Project-BSE4101-24-Employee-management-system#14]
We need to set up a Continuous Integration (CI) tool to automatically trigger builds whenever code is pushed to the repository

**Comment by Masembe0757** [comment]
As if it was already set up

**Comment by AnthonyByansi** [comment]
Yeah!

**Comment by AnthonyByansi** [comment]
Done already!
