### ISSUE TITLE
Set up production environment and pipeline  on Azure App Service Plans

### ISSUE THREAD

**Issue by AnthonyByansi** [Masembe0757/Capstone-Project-BSE4101-24-Employee-management-system#30]
Requirements:

- Create and configure Azure App Service Plans.
- Set up the CI/CD pipeline using Azure DevOps or GitHub Actions.

- Automate deployment processes to Azure.

- Implement monitoring and logging via Azure Application Insights.

- Document the setup and deployment process.

**Comment by Boniface-devote** [comment]
done
